### PR TITLE
Update the implementation name of a RakNet protocol

### PR DESCRIPTION
**Pull request by ghost**
No longer required

### CODE REVIEW

**Comment by whirvis** [comment]
I'm assuming JungleTree RakNet is now dead, and that MineRakNet is the replacement?

**EDIT**: I've changed the JungleTree data back to the way it was and added a MineRakNet connection type with the correct data along with the new ID of 0x0F. Is it possible for you to update the ID in your software to match this new ID? If so, let me know and I will approve of the pull request, merge it, and release a new version. The reason I changed the ID to 0x0F was because once an ConnectionType is added I do not change its ID under any circumstance. JungleTree used to have its own RakNet implementation so I added it. The implementation you are referring to is a completely new implementation made in an entirely new language.

**Comment by Whirvis** [comment]
Is it possible for you to update the ID to 0x0F? Since 0x0E has already been added, it is not a good idea to change it. It would probably be better to just add another connection type with the ID 0x0F.

**Comment by ojbr** [comment]
No, the JungleTree RakNet was never published. It is preferred that we use 0x0E.

**Comment by ghost** [comment]
No longer required

**Pull request closed without merging**
