### PR TITLE
Update protocol version

### LINKED ISSUE #126: Can't connect to some servers
There are some Minecraft servers, that I can't seem to connect to. For example, versai.pro, it is running the latest version of Pocketmine, but probably has some modifications. You can connect to it through the Minecraft client, but cannot through this library, it just says that the server is offline. The only thing I know is that the server may send an invalid MTU, and that may cause this issue.

### PR DESCRIPTION
**Pull request by Saehing**

### CODE REVIEW

**Comment by whirvis** [comment]
Thank you very much for this pull request! I will merge it when I can. I realize there are two other issues on the repository still, and I apologize that they have not been fixed yet. I have been busy with other projects and busy with stuff in my personal life.

**Comment by whirvis** [comment]
This may also be the cause of #126.

**Comment by kanjiman** [comment]
Not to be a bother, but is there any updates on the new protocol being added?

**Comment by kanjiman** [comment]
Nevermind, this solution works. Just make sure you have the maven dependencies or it will error.
`
[21:30:13] [Server thread/INFO]: Done (0.792s)! For help, type "help" or "?"
[21:30:23] [Server thread/INFO]: [/98.193.45.162:51206] logged out due to client disconnect
`
successful connection to an mcpe 1.16.20 server with protocol 10

**Comment by Ckblck** [comment]
This PR fixes if I am not wrong two of the current issues, I was also in the same situation in which I could not connect to the server due to this problem. Building a new version with this change fixed the issue.

**Pull request merged**
