### PR TITLE
Removing Joda time, RakNetLogger, Adding SLF4J

### PR DESCRIPTION
**Pull request by TheStackTraceWhisperer**
1) Pulled out Joda time, couldn't find any references in library.  If more up-to-date time classes are needed JDK 1.8 added java.time.* (see JSR 310 for more details)

2) **API-Breaking**: Removed RakNetLogger in favor of SLF4J's logging api which gives developers the ability to plug in any logging backend they want.
- Should have minimal regression regarding logging content and output during unit test expectations (added slf4j-simple as a test dependency)
- Expect larger regressions against code bases that depended on isLoggingEnabled, enableLogging, disableLogging, and similarly removed methods.  Since logging is handled on a per-class basis I do not believe these are needed.  Each class should have access to its own Logger instance to allow for the greatest flexibility in logging.

### CODE REVIEW

**Comment by whirvis** [comment]
Thank you for this pull request! I will go over everything as soon as possible and merge when possible. If I do merge, I will rebuild and post a new version for JRakNet :)

**Review by whirvis — COMMENTED** [review]
So far this pull request looks really good. There are a few inconcistencies in the code and some that look like straight up errors. However, I still need to see what this would look like in an actual IDE so I can't say for sure. However, I did notice anything that had "log" seemed to get removed. For example, "logging" got changed to "ging" and "login" got changed to "in" Did you do a search and replace?

**Comment by TheStackTraceWhisperer** [comment]
I did once, but I had thought I fixed most of those occurrences.  I'll go back and do a fresh take on this tomorrow evening.

**Comment by MarfGamer** [comment]
Thanks for making those fixes! I'll try and get this merged by friday

**Comment by whirvis** [comment]
Everything is looking good so far! I went on and added the Log4J2 implementation for SLF4J to the maven POM, and also fixed up some small errors (Unused imports, unused logger objects in classes that didn't use them, etc.) I really appreciate that you added this to JRakNet, have a wonderful day!

**Pull request merged**
